### ISSUE TITLE
timeshift restore fails with segfault

### ISSUE THREAD

**Issue by MiesSuomesta** [teejee2008/timeshift#655]
/dev/sdb2 is mounted at: /run/timeshift/backup, options: rw,relatime

[New Thread 0x7ffff3190700 (LWP 28776)]
[Detaching after fork from child process 28777]
[Detaching after fork from child process 28778]

******************************************************************************
To restore with default options, press the ENTER key for all prompts!
******************************************************************************

Press ENTER to continue...

Re-install GRUB2 bootloader? (recommended) (y/n): [New Thread 0x7ffff293f700 (LWP 28779)]
y

Select GRUB device:

[Detaching after fork from child process 28780]
Num     Device  Description                        
------------------------------------------------------------------------------
0    >  sda     ATA Samsung_SSD_870_QVO_2TB [MBR]  
1    >  sda1     ext4,  2.0 GB GB                  
2    >  sda2     ext4, 118.5 GB GB                 
3    >  sda5     ext4, 1879.4 GB GB                
4    >  sdb     Kingston DataTraveler_3.0 [MBR]    
5    >  sdb2     ext4, 58.6 GB GB, writable        

Enter device name or number (a=Abort): [New Thread 0x7ffff213e700 (LWP 28781)]
[Thread 0x7ffff293f700 (LWP 28779) exited]
1

******************************************************************************
GRUB Device: /dev/sda1
******************************************************************************

Thread 1 "timeshift" received signal SIGSEGV, Segmentation fault.
0x00005555555722c3 in ?? ()
(gdb) bt full
#0  0x00005555555722c3 in ?? ()
No symbol table info available.
#1  0x000055555557310c in ?? ()
No symbol table info available.
#2  0x00005555555b93a5 in ?? ()
No symbol table info available.
#3  0x00005555555bb303 in ?? ()
No symbol table info available.
#4  0x00007ffff6d8d0b3 in __libc_start_main (main=0x555555561960, argc=8, argv=0x7fffffffe038, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffe028) at ../csu/libc-start.c:308
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {93824992656272, 64280180862776670, 93824992287104, 140737488347184, 0, 0, -64280179802081954, 
                -64260088384031394}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x8, 0x7fffffffe038}, data = {prev = 0x0, cleanup = 0x0, canceltype = 8}}}
        not_first_call = <optimized out>
#5  0x00005555555619ae in ?? ()
No symbol table info available.
(gdb) 

[dumppi.txt](https://github.com/teejee2008/timeshift/files/5341398/dumppi.txt)

**Note:** If you are a Linux Mint user and you need help with an issue, consider posting the issue on [Linux Mint forums](https://forums.linuxmint.com) where there are more people to help you out.

**Describe the bug**
Segmentation fault when restoring.

**To Reproduce**
try to restore.

**Expected behavior**

**Screenshots**

**System:**
 Desktop : Gnome

# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

**Comment by CGA11** [comment]
Same issue for me running aarch64 on arm.
